name: shell commands 

on:
  - push

#env:
#   ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.4.0
        with:
          terraform_version: 1.4.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
         ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
         AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
         aws-region: us-east-1
      - name: Terraform init
        run: terraform init   
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan  